name: CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  build_and_push_docker_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/innovate-mart-backend:latest

      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/innovate-mart-frontend:latest
  
  deploy_to_eks:
    runs-on: ubuntu-latest
    needs: build_and_push_docker_images
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Update Kubernetes Manifests
        run: |
          sed -i 's/DOCKER_HUB_USERNAME/${{ secrets.DOCKER_HUB_USERNAME }}/g' kubernetes/backend-deployment.yaml
          sed -i 's/DOCKER_HUB_USERNAME/${{ secrets.DOCKER_HUB_USERNAME }}/g' kubernetes/frontend-deployment.yaml

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.23.0'

      - name: Install eksctl
        run: |
          curl --silent --location "https://github.com/weaveworks/eksctl/releases/download/v0.111.0/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin

      - name: Get kubeconfig
        run: eksctl utils write-kubeconfig --cluster=innovate-mart-cluster --region=us-east-1

      - name: Deploy to EKS
        run: |
          kubectl apply -f kubernetes/
