name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [catalog, orders, carts]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image for ${{ matrix.service }}
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.service }}-service
          file: ./${{ matrix.service }}-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ matrix.service }}-service:latest

  deploy-to-eks:
    runs-on: ubuntu-latest
    needs: build-and-push-images
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: '1.24.0'

      - name: Configure Kubeconfig
        run: aws eks update-kubeconfig --name innovatemart-eks-cluster --region eu-west-1

      - name: Update deployment image tags
        run: |
          sed -i "s|innovatemart/catalog-service:latest|${{ secrets.DOCKER_HUB_USERNAME }}/catalog-service:latest|g" kubernetes/deployment.yml
          sed -i "s|innovatemart/orders-service:latest|${{ secrets.DOCKER_HUB_USERNAME }}/orders-service:latest|g" kubernetes/deployment.yml
          sed -i "s|innovatemart/carts-service:latest|${{ secrets.DOCKER_HUB_USERNAME }}/carts-service:latest|g" kubernetes/deployment.yml
        
      - name: Deploy to EKS
        run: |
          kubectl apply -f kubernetes/deployment.yml
          kubectl apply -f kubernetes/service.yml

